# Generated by Django 5.0.4 on 2024-04-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_word', models.CharField(max_length=100)),
                ('replaced_word', models.CharField(max_length=100)),
            ],
        ),
    ]
